declare const classNames: {
  readonly askModal: "askModal";
  readonly askModalContent: "askModalContent";
  readonly askWrapper: "askWrapper";
  readonly askWrapperInner: "askWrapperInner";
  readonly messageWrapper: "messageWrapper";
  readonly meContainer: "meContainer";
  readonly me: "me";
  readonly errorBtn: "errorBtn";
  readonly errorIcon: "errorIcon";
  readonly opContainer: "opContainer";
  readonly op: "op";
  readonly reviewContainer: "reviewContainer";
  readonly review: "review";
  readonly thumbIcon__good: "thumbIcon__good";
  readonly thumbIcon__navigator: "thumbIcon__navigator";
  readonly op_streamContainer: "op_streamContainer";
  readonly op_streamContainer__loading: "op_streamContainer__loading";
  readonly askModalAlertContainer: "askModalAlertContainer";
  readonly textAreaContainer: "textAreaContainer";
  readonly textArea: "textArea";
  readonly errorTip: "errorTip";
};
export = classNames;
